(()=>{'use strict';const $=id=>document.getElementById(id);let relations=[],query='';
const message=s=>$('status').textContent=s;
async function api(path,data){const r=await fetch(path,{method:data?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
function empty(el,text){el.replaceChildren();const p=document.createElement('p');p.className='friends-empty';p.textContent=text;el.append(p)}
function button(text,fn,secondary=false){const b=document.createElement('button');b.type='button';b.textContent=text;if(secondary)b.className='secondary';b.addEventListener('click',async()=>{b.disabled=true;try{await fn();await load()}catch(e){message(e.message)}finally{b.disabled=false}});return b}
function card(p,kind){const el=document.createElement('div');el.className='friend-card';const info=document.createElement('div');const name=document.createElement('strong');name.textContent='@'+p.username;const team=document.createElement('small');team.textContent=p.team_name||'No saved Dream Team';info.append(name,team);const actions=document.createElement('div');actions.className='friend-actions';const profile=document.createElement('a');profile.href='/profile.html?username='+encodeURIComponent(p.username);profile.textContent='Profile';actions.append(profile);
if(kind==='friend'){if(p.team_name){const play=document.createElement('a');play.href='/dream-match.html?opponent='+encodeURIComponent(p.username);play.textContent='⚔ Challenge';actions.append(play)}actions.append(button('Remove',()=>api('/api/friends',{action:'remove',id:p.id}),true))}
if(kind==='incoming'){actions.append(button('✓ Accept',()=>api('/api/friends',{action:'accept',id:p.id})));actions.append(button('Decline',()=>api('/api/friends',{action:'decline',id:p.id}),true))}
if(kind==='outgoing')actions.append(button('Cancel',()=>api('/api/friends',{action:'cancel',id:p.id}),true));
if(kind==='search'){const rel=relations.find(r=>r.username===p.username);if(rel){const state=document.createElement('small');state.textContent=rel.status==='accepted'?'✓ Friends':rel.outgoing?'Request sent':'Request received';actions.append(state)}else actions.append(button('+ Add Friend',()=>api('/api/friends',{action:'request',username:p.username})))}
el.append(info,actions);return el}
async function load(){try{const data=await api('/api/friends'+(query?'?q='+encodeURIComponent(query):''));relations=data.friends;const friends=relations.filter(r=>r.status==='accepted'),incoming=relations.filter(r=>r.status==='pending'&&!r.outgoing),outgoing=relations.filter(r=>r.status==='pending'&&r.outgoing);$('friendCount').textContent=friends.length;$('requestCount').textContent=incoming.length;for(const [id,rows,kind,placeholder] of [['friends',friends,'friend','No friends yet. Search above to add one!'],['incoming',incoming,'incoming','No new friend requests.'],['outgoing',outgoing,'outgoing','No pending sent requests.'],['results',data.results,'search',query?'No matching players found.':'Search for players to add.']]){const el=$(id);el.replaceChildren();if(!rows.length)empty(el,placeholder);else rows.forEach(p=>el.append(card(p,kind)))}message('Friends list is up to date.')}catch(e){message(e.message);if(/Log in/i.test(e.message)){$('status').append(' ');const a=document.createElement('a');a.href='/account.html?next=/friends.html';a.textContent='Log in →';$('status').append(a)}}}
$('searchForm').addEventListener('submit',e=>{e.preventDefault();query=$('search').value.trim();if(query.length<2){message('Enter at least two characters to search.');return}load()});load()})();