(()=>{'use strict';const $=id=>document.getElementById(id);fetch('/api/league',{credentials:'same-origin'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'League unavailable');$('status').textContent=d.standings.length+' ranked Dream Teams · 3 points per win';const t=$('standings');t.replaceChildren();for(const p of d.standings){const tr=document.createElement('tr');for(const value of ['#'+p.rank,p.username,p.team_name,p.wins,p.losses,p.points]){const td=document.createElement('td');if(value===p.username){const a=document.createElement('a');a.href='/profile.html?username='+encodeURIComponent(p.username);a.textContent='@'+p.username;td.append(a)}else td.textContent=value;tr.append(td)}t.append(tr)}if(!d.standings.length)t.textContent='No saved teams yet.'}).catch(e=>$('status').textContent=e.message)})();
(()=>{'use strict';const $=id=>document.getElementById(id);let season=null,busy=false;
const api=async(action)=>{const response=await fetch('/api/season',{method:action?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:action?JSON.stringify({action}):undefined});const result=await response.json().catch(()=>({}));if(!response.ok)throw Error(result.error||'Season request failed');return result};
function render(data){season=data.season;const content=$('seasonContent'),next=$('nextWeek');content.hidden=!season;next.hidden=!season||season.finished;
if(!season){$('seasonStatus').textContent='Start a season with at least two saved Dream Teams. Sign in and save your own team first.';return}
$('seasonStatus').textContent=season.finished?'🏆 Season complete! Start a new season to play again.':'Your league is ready. Simulate the next week to advance the season.';
$('seasonWeek').textContent=season.currentWeek+' / '+season.rounds.length;$('seasonTeams').textContent=season.teams.length;$('seasonPhase').textContent=season.finished?'FINAL':season.currentWeek===0?'PRESEASON':'IN PROGRESS';
const tbody=$('seasonStandings');tbody.replaceChildren();for(const row of data.standings){const tr=document.createElement('tr');for(const value of [row.rank,row.name,row.wins,row.losses,row.for,row.against,row.diff>0?'+'+row.diff:row.diff,row.points]){const td=document.createElement('td');td.textContent=String(value);tr.append(td)}tbody.append(tr)}
const schedule=$('seasonSchedule');schedule.replaceChildren();for(const round of season.rounds){const details=document.createElement('details');details.className='season-round';details.open=round.week===season.currentWeek+1||(season.finished&&round.week===season.currentWeek);const summary=document.createElement('summary');summary.textContent='Week '+round.week+' · '+(round.games.every(g=>g.result)?'Final':'Upcoming');details.append(summary);for(const game of round.games){const line=document.createElement('div');line.className='season-game';const home=season.teams[game.home],away=season.teams[game.away];const names=document.createElement('span');names.textContent=home.name+' vs '+away.name;const score=document.createElement('strong');score.textContent=game.result?game.result.scores.join(' – '):'Scheduled';line.append(names,score);details.append(line)}schedule.append(details)}
}
async function action(type){if(busy)return;if(type==='create'&&season&&!confirm('Replace your existing season? All current season results will be lost.'))return;busy=true;$('createSeason').disabled=true;$('nextWeek').disabled=true;$('seasonStatus').textContent=type==='create'?'Building your season…':'Simulating this week…';try{render(await api(type))}catch(e){$('seasonStatus').textContent=e.message}finally{busy=false;$('createSeason').disabled=false;$('nextWeek').disabled=false}}
$('createSeason').addEventListener('click',()=>action('create'));$('nextWeek').addEventListener('click',()=>action('advance'));api().then(render).catch(e=>$('seasonStatus').textContent=e.message);
})();