(()=>{'use strict';const $=id=>document.getElementById(id),params=new URLSearchParams(location.search);let code=params.get('code')?.trim().toUpperCase()||'',username='',lobby=null,busy=false;
const status=s=>$('status').textContent=s;
async function api(path,data){const r=await fetch(path,{method:data?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
const invite=()=>location.origin+'/season.html?code='+encodeURIComponent(code);
const next=()=>'/season.html?code='+encodeURIComponent(code);
function show(id,visible){$(id).hidden=!visible}
function render(d){lobby=d.lobby;const l=lobby;show('lobbyPanel',true);show('createPanel',false);$('lobbyName').textContent=l.name;$('lobbyState').textContent=l.status==='open'?'PRESEASON · INVITE FRIENDS':'SEASON IN PROGRESS';$('hostLabel').textContent='Hosted by @'+l.host;$('inviteUrl').textContent=invite();$('memberCount').textContent=l.memberCount+' / 12';const list=$('members');list.replaceChildren();for(const m of l.members){const row=document.createElement('div');row.className='member';const info=document.createElement('div'),name=document.createElement('strong'),team=document.createElement('small'),state=document.createElement('span');name.textContent='@'+m.username+(m.username===l.host?' 👑':'');team.textContent=m.teamName||'Dream Team not built yet';state.textContent=m.ready?'✓ TEAM READY':'⏳ NEEDS DREAM TEAM';state.className=m.ready?'ready':'pending';info.append(name,team);row.append(info,state);list.append(row)}
show('joinLeague',l.status==='open'&&!!username&&!l.joined);show('signIn',!username);show('buildTeam',l.status==='open'&&l.joined&&!l.members.find(m=>m.username===username)?.ready);show('startLeague',l.status==='open'&&l.owner);show('openSeason',l.status!=='open'&&l.joined);$('startLeague').disabled=!l.canStart;$('openSeason').href='/league.html?code='+encodeURIComponent(code);$('buildTeam').href='/builder.html?seasonCode='+encodeURIComponent(code);$('signIn').href='/account.html?next='+encodeURIComponent(next());$('lobbyHint').textContent=l.status!=='open'?'Season is underway! Open standings to see games and replays.':!l.joined?'Join this league, then build and save your Dream Team.':l.canStart?'All teams are ready. The commissioner can start the season!':'Invite at least one more friend. Everyone must save a valid 22-Pokémon Dream Team before the season can begin.';status('League ready · '+l.memberCount+' friends joined.')}
async function loadLobby(){try{const d=await api('/api/season-invite?code='+encodeURIComponent(code));render(d)}catch(e){status(e.message);show('createPanel',true)}}
async function loadMine(){if(!username){$('myLeagues').textContent='Create a profile or sign in to see your leagues.';return}try{const d=await api('/api/season-lobby');const el=$('myLeagues');el.replaceChildren();if(!d.lobbies.length)el.textContent='No leagues yet. Create one above or open a friend’s invite.';for(const l of d.lobbies){const a=document.createElement('a');a.href='/season.html?code='+encodeURIComponent(l.code);a.textContent=(l.owner?'👑 ':'🏈 ')+l.name+' · '+(l.status==='open'?'Waiting for players':'Season active');el.append(a)}}catch(e){$('myLeagues').textContent=e.message}}
async function mutate(action,data={}){if(busy)return;busy=true;try{status('Saving league…');const d=await api('/api/season-lobby',{action,code,...data});if(d.lobby){code=d.lobby.code;history.replaceState(null,'','/season.html?code='+encodeURIComponent(code));render(d)}await loadMine()}catch(e){status(e.message)}finally{busy=false}}
$('createForm').onsubmit=e=>{e.preventDefault();if(!username){location.href='/account.html?next='+encodeURIComponent('/season.html');return}mutate('create',{name:$('leagueName').value.trim()})};
$('joinLeague').onclick=()=>mutate('join');$('startLeague').onclick=()=>{if(confirm('Start the season with these teams? New players cannot join after kickoff.'))mutate('start')};$('refresh').onclick=loadLobby;
$('copyLink').onclick=async()=>{try{await navigator.clipboard.writeText(invite());status('✓ Invite link copied! Send it to your friends.')}catch{status('Copy this link: '+invite())}};
$('shareLink').onclick=async()=>{const text='Join my Gridiron 151 Pokémon football season! Create your profile, build a Dream Team, and compete: ';if(navigator.share){try{await navigator.share({title:lobby?.name||'Friends Season',text,url:invite()})}catch(e){if(e.name!=='AbortError')status(e.message)}}else{try{await navigator.clipboard.writeText(text+invite());status('✓ Invitation copied for your group chat!')}catch{status(text+invite())}}};
(async()=>{try{const d=await api('/api/auth/me');username=d.user?.username||''}catch{}if(code)await loadLobby();else{show('createPanel',true);status('Create a league or open a friend’s invitation.')}await loadMine()})();})();