(()=>{'use strict';const $=id=>document.getElementById(id),params=new URLSearchParams(location.search);let code=(params.get('code')||'').trim().toUpperCase(),username='',lobby=null,busy=false;
function show(id,on){$(id).hidden=!on}
function status(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error)}
async function api(path,payload){const r=await fetch(path,{method:payload?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:payload?JSON.stringify(payload):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Something went wrong. Try again.');return d}
const invite=()=>location.origin+'/season.html?code='+encodeURIComponent(code);
function step(id,phase){$(id).classList.toggle('current',phase==='current');$(id).classList.toggle('done',phase==='done')}
function render({lobby:l}){lobby=l;show('welcome',false);show('welcomeHero',false);show('lobbyPanel',true);show('newLeagueLink',true);$('lobbyName').textContent=l.name;$('lobbyState').textContent=l.status==='open'?'PRESEASON · LEAGUE LOBBY':l.status==='finished'?'SEASON COMPLETE':'SEASON UNDERWAY';$('hostLabel').textContent='Commissioner: @'+l.host;$('memberCount').textContent=l.memberCount+' / 12';$('inviteUrl').value=invite();
const roster=$('members');roster.replaceChildren();for(const m of l.members){const row=document.createElement('div');row.className='member';const avatar=document.createElement('span');avatar.className='avatar';avatar.textContent=m.username===l.host?'👑':'🏈';const info=document.createElement('div');info.className='member-info';const name=document.createElement('strong');name.textContent='@'+m.username;const team=document.createElement('small');team.textContent=m.teamName||'Team not saved yet';info.append(name,team);const flag=document.createElement('span');flag.className=m.ready?'ready':'pending';flag.textContent=m.ready?'✓ READY':'○ NOT READY';row.append(avatar,info,flag);roster.append(row)}
const active=l.status!=='open',joined=l.joined,me=l.members.find(m=>m.username===username),ready=!!me?.ready;show('inviteSection',!active&&joined);show('signIn',!username&&!active);show('joinLeague',!!username&&!joined&&!active);show('buildTeam',joined&&!ready&&!active);show('startLeague',l.owner&&!active);show('openSeason',joined&&active);$('startLeague').disabled=!l.canStart;$('openSeason').href='/league.html?code='+encodeURIComponent(code);$('buildTeam').href='/builder.html?seasonCode='+encodeURIComponent(code);$('signIn').href='/account.html?next='+encodeURIComponent('/season.html?code='+code);
let title,description,phase;
if(active){title=l.status==='finished'?'Season complete!':'The season is underway!';description='Check standings, weekly scores, and watch the games.';phase=3}
else if(!username){title='Create your player profile';description='Choose a username to join this league. Your invitation will be waiting when you return.';phase=1}
else if(!joined){title='Join '+l.name;description='You’re one click away from joining the league. Build your team after you join.';phase=1}
else if(!ready){title='Build your Dream Team';description='Pick 22 Pokémon within the $300 cap and save your roster to get game-ready.';phase=2}
else if(l.canStart&&l.owner){title='Everyone is ready. Kick off!';description='All teams are set. Start the season to generate fixtures and standings.';phase=3}
else if(l.owner){title='Invite your friends';description='Share the link below. You need at least two saved teams to start.';phase=1}
else{title='You’re in! Waiting for kickoff';description='Your team is ready. Share the invite or wait for the commissioner to start.';phase=3}
$('actionTitle').textContent=title;$('actionDescription').textContent=description;$('actionEyebrow').textContent=active?'SEASON DASHBOARD':'YOUR NEXT STEP';step('stepInvite',phase===1?'current':'done');step('stepTeams',phase===2?'current':phase>2?'done':'');step('stepKickoff',phase===3?'current':'');$('lobbyHint').textContent=active?'Your league and results are saved.':l.canStart?'All teams are ready for kickoff.':l.members.filter(m=>m.ready).length+' of '+l.memberCount+' players have saved their teams.';status(l.name+' · '+l.memberCount+' joined · '+l.members.filter(m=>m.ready).length+' ready')}
async function loadLobby(){try{render(await api('/api/season-invite?code='+encodeURIComponent(code)))}catch(e){status(e.message,true);show('welcome',true);show('welcomeHero',true);show('lobbyPanel',false)}}
async function loadMine(){if(!username){$('myLeagues').textContent='Sign in to see leagues you have joined.';return}try{const d=await api('/api/season-lobby'),el=$('myLeagues');el.replaceChildren();if(!d.lobbies.length){el.textContent='No leagues yet. Create one or join a friend’s invite.';return}for(const l of d.lobbies){const a=document.createElement('a');a.href='/season.html?code='+encodeURIComponent(l.code);const label=document.createElement('span'),tag=document.createElement('small');label.textContent=(l.owner?'👑 ':'🏈 ')+l.name;tag.textContent=l.status==='open'?'Preseason':l.status==='finished'?'Finished':'In season';a.append(label,tag);el.append(a)}}catch(e){$('myLeagues').textContent=e.message}}
async function mutate(action,data={}){if(busy)return;busy=true;status('Saving your league…');try{const d=await api('/api/season-lobby',{action,code,...data});if(d.lobby){code=d.lobby.code;history.replaceState(null,'','/season.html?code='+encodeURIComponent(code));render(d)}await loadMine()}catch(e){status(e.message,true)}finally{busy=false}}
$('createForm').addEventListener('submit',e=>{e.preventDefault();if(!username){sessionStorage.setItem('gridiron_pending_league_name',$('leagueName').value.trim());location.href='/account.html?next='+encodeURIComponent('/season.html?create=1');return}mutate('create',{name:$('leagueName').value.trim()})});
$('joinForm').addEventListener('submit',e=>{e.preventDefault();const value=$('joinCode').value.trim().toUpperCase();if(!/^[A-F0-9]{10}$/.test(value)){status('Enter the 10-character code from your invitation.',true);return}location.href='/season.html?code='+encodeURIComponent(value)});
$('joinLeague').onclick=()=>mutate('join');$('startLeague').onclick=()=>{if(confirm('Start the season? No new players can join after kickoff.'))mutate('start')};$('refresh').onclick=loadLobby;
$('copyLink').onclick=async()=>{try{await navigator.clipboard.writeText(invite());$('copyLink').textContent='✓ Copied!';status('Invite copied. Paste it into your group chat.')}catch{const input=$('inviteUrl');input.focus();input.select();status('Copy the selected invite link.')}};
$('shareLink').onclick=async()=>{const message='Join my Gridiron 151 Pokémon football league!';if(navigator.share){try{await navigator.share({title:lobby?.name||'Friends League',text:message,url:invite()})}catch(e){if(e.name!=='AbortError')status(e.message,true)}}else{$('copyLink').click()}};
(async()=>{try{const d=await api('/api/auth/me');username=d.user?.username||''}catch{}if(code){await loadLobby()}else{show('welcome',true);show('welcomeHero',true);status('Choose how you want to play.')}await loadMine();if(!code&&username&&params.get('create')==='1'){const name=sessionStorage.getItem('gridiron_pending_league_name');if(name){sessionStorage.removeItem('gridiron_pending_league_name');$('leagueName').value=name;await mutate('create',{name})}}})();})();