(()=>{'use strict';
const $=id=>document.getElementById(id),username=(new URLSearchParams(location.search).get('username')||'').trim().toLowerCase(),url=location.origin+'/team.html?username='+encodeURIComponent(username);
const sprite=id=>'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/'+id+'.png';
const coords={FS:[38,8],SS:[62,8],CB1:[10,23],CB2:[90,23],LB1:[32,25],LB2:[50,25],LB3:[68,25],DE1:[24,40],DT1:[41,40],DT2:[59,40],DE2:[76,40],WR1:[9,61],WR2:[91,61],WR3:[18,80],TE:[78,61],LT:[30,61],LG:[40,61],C:[50,61],RG:[60,61],RT:[70,61],QB:[50,80],RB:[50,94]};
const roles={QB:'Quarterback',RB:'Running back',WR1:'Wide receiver',WR2:'Wide receiver',WR3:'Slot receiver',TE:'Tight end',LT:'Left tackle',LG:'Left guard',C:'Center',RG:'Right guard',RT:'Right tackle',DE1:'Defensive end',DE2:'Defensive end',DT1:'Defensive tackle',DT2:'Defensive tackle',LB1:'Linebacker',LB2:'Middle linebacker',LB3:'Linebacker',CB1:'Cornerback',CB2:'Cornerback',FS:'Free safety',SS:'Strong safety'};
const offense=['QB','RB','WR1','WR2','WR3','TE','LT','LG','C','RG','RT'];
const invite='Think your Pokémon football team can beat mine? Check out my Gridiron 151 Dream Team and build your own: '+url;
function row(p){const card=document.createElement('div');card.className='share-player';const img=document.createElement('img');img.src=sprite(p.id);img.alt='';img.loading='lazy';const info=document.createElement('div'),name=document.createElement('strong'),pos=document.createElement('small'),price=document.createElement('b');name.textContent=p.name;pos.textContent=p.position+' · '+(roles[p.position]||'Starter');price.textContent='$'+p.salary;info.append(name,pos);card.append(img,info,price);return card}
function detail(p,button){document.querySelectorAll('.field-mon.selected').forEach(n=>n.classList.remove('selected'));button.classList.add('selected');$('detailSprite').src=sprite(p.id);$('detailSprite').alt=p.name;$('detailRole').textContent=p.position+' / '+(roles[p.position]||'Starter');$('detailName').textContent=p.name;$('detailPrice').textContent='$'+p.salary+' salary';$('playerDetail').hidden=false}
$('detailClose').onclick=()=>{$('playerDetail').hidden=true;document.querySelectorAll('.field-mon.selected').forEach(n=>n.classList.remove('selected'))};
function fieldPlayer(p){const point=coords[p.position];if(!point)return;const btn=document.createElement('button');btn.type='button';btn.className='field-mon '+(offense.includes(p.position)?'offense-mon':'defense-mon');btn.style.left=point[0]+'%';btn.style.top=point[1]+'%';btn.title=p.name+' · '+(roles[p.position]||p.position)+' · $'+p.salary;btn.setAttribute('aria-label',btn.title);const img=document.createElement('img');img.src=sprite(p.id);img.alt='';img.loading='lazy';const label=document.createElement('span');label.className='mon-label';const name=document.createElement('strong');name.textContent=p.name;const role=document.createElement('small');role.textContent=p.position;label.append(name,role);btn.append(img,label);btn.onclick=()=>detail(p,btn);$('fieldPlayers').append(btn)}
async function load(){try{if(!/^[a-z0-9_]{3,24}$/.test(username))throw Error('This invite link is missing a valid trainer username.');const response=await fetch('/api/shared-team?username='+encodeURIComponent(username),{cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error||'Team unavailable');document.title=data.name+' · Gridiron 151 Dream Team';$('headline').replaceChildren(document.createTextNode(data.name+' '));const em=document.createElement('em');em.textContent='DREAM TEAM';$('headline').append(em);$('trainer').textContent='@'+data.username;$('salary').textContent='$'+data.totalSalary+' / $'+data.salaryCap;$('starters').textContent=data.players.length+'/22';$('subtitle').textContent='@'+data.username+' built this squad. Scout all 22 Pokémon on the field, then build a team that can beat it.';const byPosition=new Map(data.players.map(p=>[p.position,p]));for(const position of [...offense,...Object.keys(coords).filter(p=>!offense.includes(p))]){const p=byPosition.get(position);if(!p)continue;fieldPlayer(p);$(offense.includes(position)?'offense':'defense').append(row(p))}const challenge='/dream-match.html?opponent='+encodeURIComponent(data.username);$('challenge').href=challenge;$('challengeTop').href=challenge;$('buildInvite').href='/builder.html?invitedBy='+encodeURIComponent(data.username);$('buildBottom').href=$('buildInvite').href;$('status').textContent=data.valid?'✓ Complete roster · Ready for Dream Team battles':'Roster needs updating before battles'}catch(e){$('status').textContent=e.message;$('buildInvite').href='/builder.html';$('buildBottom').href='/builder.html'}}
$('copyInvite').onclick=async()=>{try{await navigator.clipboard.writeText(invite);$('copyInvite').textContent='✓ Link Copied!'}catch{const input=document.createElement('textarea');input.value=invite;document.body.append(input);input.select();document.execCommand('copy');input.remove();$('copyInvite').textContent='✓ Link Copied!'}};load()})();