(()=>{'use strict';const $=id=>document.getElementById(id);let data=null,play='',position='',busy=false;const sprite=id=>'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/'+id+'.png';
async function api(body){const r=await fetch('/api/showdown',{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Could not load game.');return d}
function msg(s){$('message').textContent=s}
function choose(type,value){if(type==='play')play=value;else position=value;drawChoices()}
function drawChoices(){if(!data?.game||data.game.finished)return;const g=data.game,offense=g.turn==='offense',calls=offense?data.plays:data.defenses;const pb=$('playbook');pb.replaceChildren();for(const [key,v] of Object.entries(calls)){const btn=document.createElement('button');btn.type='button';btn.className='choice'+(play===key?' selected':'');const title=document.createElement('strong');title.textContent=v.name;const sub=document.createElement('small');sub.textContent=offense?(key==='run'?'Grind out yards':key==='pass'?'Attack downfield':key==='screen'?'Punish the blitz':'Surprise the defense'):(key==='blitz'?'Pressure the passer':key==='zone'?'Contain quick passes':'Stop the run');btn.append(title,sub);btn.onclick=()=>choose('play',key);pb.append(btn)}
 const list=$('abilities');list.replaceChildren();for(const p of data.options){const btn=document.createElement('button');btn.type='button';btn.className='choice'+(position===p.position?' selected':'');btn.disabled=p.cooldown>0;const title=document.createElement('strong');title.textContent=p.name+' · '+p.position;const sub=document.createElement('small');sub.textContent=p.cooldown?'⏳ '+p.cooldown+' snap(s) remaining':p.move+' — '+p.description;btn.append(title,sub);btn.onclick=()=>choose('position',p.position);list.append(btn)}$('snap').disabled=!play||!position||busy;$('selectedSummary').textContent=play&&position?calls[play]?.name+' + '+(data.options.find(p=>p.position===position)?.move||'Ability'):'Choose a play and Pokémon.'}
const POSITIONS=['QB','RB','WR1','WR2','WR3','TE','LT','LG','C','RG','RT','DE1','DE2','DT1','DT2','LB1','LB2','LB3','CB1','CB2','FS','SS'];
const COORDS={QB:[-13,55],RB:[-22,55],WR1:[-17,8],WR2:[-17,92],WR3:[-22,26],TE:[-5,85],LT:[-4,31],LG:[-4,43],C:[-4,55],RG:[-4,67],RT:[-4,79],DE1:[4,23],DE2:[4,83],DT1:[4,43],DT2:[4,65],LB1:[14,24],LB2:[14,55],LB3:[14,82],CB1:[22,8],CB2:[22,92],FS:[29,36],SS:[29,72]};
const spriteNodes=new Map();const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));let animating=false;
function setSpot(node,x,y){node.style.left=x+'%';node.style.top=y+'%'}
function field(g){const root=$('fieldSprites');root.replaceChildren();spriteNodes.clear();const line=9+g.ball*.82;const ball=$('ballMarker');ball.style.left=line+'%';ball.style.top='48%';ball.classList.remove('ball-flight');
 for(const side of ['player','ai']){const ids=side==='player'?POSITIONS.map(pos=>g.playerLineup[pos]):g.aiLineup;POSITIONS.forEach((pos,i)=>{const id=ids[i];if(!id)return;const offenseSide=side===(g.turn==='offense'?'player':'ai');const point=COORDS[pos];const sign=offenseSide?-1:1;const x=Math.max(4,Math.min(96,line+sign*Math.abs(point[0])*.62));const y=point[1];const el=document.createElement('div');el.className='field-sprite '+(side==='player'?'home-sprite':'away-sprite');el.dataset.side=side;el.dataset.pos=pos;setSpot(el,x,y);const img=document.createElement('img');img.src=sprite(id);img.alt=(side==='player'?'Your ':'AI ')+pos;img.loading='eager';const label=document.createElement('small');label.textContent=(side==='player'?'★ ':'')+pos;el.append(img,label);root.append(el);spriteNodes.set(side+':'+pos,{el,x,y,side,pos})})}
}
function targetFor(actor,entry){const {x,y,pos,side}=actor;const attacking=side===(entry.offense?'player':'ai');const direction=attacking?1:-1;const distance=Math.max(2,Math.min(19,Math.abs(entry.yards)*.55+4));const receiver=/^WR|TE/.test(pos),line=/^(LT|LG|C|RG|RT|DE|DT)/.test(pos),runner=pos==='RB'||pos==='QB';let dx=0,dy=0;
 if(attacking){dx=direction*(line?2.5:receiver?distance:runner?distance*.7:distance*.35);dy=receiver?(pos==='WR1'?-6:pos==='WR2'?6:pos==='WR3'?-3:3):line?(y<55?-1.5:1.5):runner?0:2}
 else{dx=direction*(line?4:pos.startsWith('LB')?7:receiver?3:5);dy=(y<55?1:-1)*(line?2:4)}
 if(entry.play==='Deep Pass'&&attacking&&receiver)dx+=direction*8;
 if(entry.play==='Power Run'&&attacking&&runner)dx+=direction*4;
 if(entry.play==='Screen Pass'&&attacking&&receiver){dx*=.45;dy+=y<55?8:-8}
 if(entry.play==='Trick Play'&&attacking&&runner)dy+=y<55?12:-12;
 if(entry.aiCall==='Thunder Blitz'&&!attacking&&line)dx+=direction*5;
 return [Math.max(3,Math.min(97,x+dx)),Math.max(9,Math.min(91,y+dy))]}
async function animateSnap(entry){if(!entry||!spriteNodes.size)return;animating=true;const ball=$('ballMarker');const before=entry.before?.ball??25;const after=entry.after?.ball??before;const start=9+before*.82;const end=9+after*.82;ball.style.transition='none';ball.style.left=start+'%';ball.style.top='48%';void ball.offsetWidth;
 const nodes=[...spriteNodes.values()];for(const actor of nodes){actor.el.classList.add('in-play');const [tx,ty]=targetFor(actor,entry);actor.el.style.transition='left 1.25s cubic-bezier(.24,.7,.35,1), top 1.25s ease-in-out, transform .3s';setSpot(actor,tx,ty)}
 ball.classList.add('ball-flight');ball.style.transition='left 1.15s ease-in-out,top .6s ease';ball.style.left=Math.max(3,Math.min(97,start+(entry.yards||0)*.82))+'%';ball.style.top=entry.play==='Deep Pass'?'25%':'48%';
 await wait(1250);ball.style.top='48%';await wait(350);for(const actor of nodes)actor.el.classList.remove('in-play');animating=false}
function feed(g){const root=$('feed');root.replaceChildren();if(!g.log.length){root.textContent='Kickoff is coming. Choose your first play.';return}for(const e of g.log){const row=document.createElement('article');const title=document.createElement('strong');title.textContent='SNAP '+e.snap+' · '+(e.offense?'YOUR OFFENSE':'YOUR DEFENSE')+' · '+e.play;const p=document.createElement('p');p.textContent=e.pokemon+' used '+e.move+'. AI: '+e.aiCall+'. '+(e.yards>=0?'+':'')+e.yards+' yards. '+e.event;row.append(title,p);root.append(row)}}
function render(d){data=d;const g=d.game;const active=!!g; $('setup').hidden=active;$('game').hidden=!active;if(!g){msg('Choose an AI opponent and start a game.');return}$('myScore').textContent=g.score[0];$('aiScore').textContent=g.score[1];$('opponentName').textContent=g.team;$('clock').textContent='Q'+g.quarter+' · SNAP '+Math.min(g.snap+1,24)+'/24';$('situation').textContent=g.down+' & '+g.toGo+' · BALL '+g.ball;$('possession').textContent=g.turn==='offense'?'YOU HAVE THE BALL':'AI HAS THE BALL';$('callHeading').textContent=g.turn==='offense'?'CALL YOUR OFFENSE':'CALL YOUR DEFENSE';$('callHint').textContent=g.turn==='offense'?'Beat the AI defensive call to gain extra yards.':'Predict the AI play and shut it down.';field(g);feed(g);if(g.finished){msg('FINAL · '+(g.winner==='player'?'YOU WIN!':g.winner==='ai'?'AI WINS':'TIE')+' · '+g.score.join(' – '));$('snap').disabled=true;$('snap').textContent='FINAL WHISTLE';$('playbook').replaceChildren();$('abilities').replaceChildren();$('selectedSummary').textContent='Game complete. Start another showdown to play again.';return}msg('Q'+g.quarter+' · '+(g.turn==='offense'?'Your offense is on the field.':'Your defense is on the field.')+' Match progress saves automatically.');if(!d.options.some(p=>p.position===position&&p.cooldown===0))position='';play='';$('snap').textContent='🏈 SNAP THE BALL →';drawChoices()}
$('start').onclick=async()=>{if(busy)return;busy=true;try{msg('Setting up your game…');render(await api({action:'start',stage:Number($('opponent').value)}))}catch(e){msg(e.message)}finally{busy=false}};
$('snap').onclick=async()=>{if(busy||!play||!position)return;busy=true;$('snap').disabled=true;try{const result=await api({action:'snap',play,position});if(result.entry){msg('🏈 '+result.entry.play+' — '+result.entry.pokemon+' uses '+result.entry.move+'!');await animateSnap(result.entry)}render(result);if(result.entry)msg(result.entry.pokemon+' used '+result.entry.move+' · '+result.entry.yards+' yards. '+result.entry.event)}catch(e){msg(e.message);drawChoices()}finally{busy=false;if(data?.game&&!data.game.finished)drawChoices()}};
$('newMatch').onclick=()=>{if(!data?.game?.finished&&!confirm('Start a new game? Your current game will be replaced.'))return;data=null;$('setup').hidden=false;$('game').hidden=true;msg('Choose your next AI opponent.')};
api().then(render).catch(e=>{msg(e.message+' Sign in and save your Dream Team to play.');$('setup').hidden=false})();})();