(()=>{'use strict';const $=id=>document.getElementById(id);let data=null,play='',position='',busy=false;const sprite=id=>'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/'+id+'.png';
async function api(body){const r=await fetch('/api/showdown',{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Could not load game.');return d}
function msg(s){$('message').textContent=s}
function choose(type,value){if(type==='play')play=value;else position=value;drawChoices()}
function drawChoices(){if(!data?.game||data.game.finished)return;const g=data.game,offense=g.turn==='offense',calls=offense?data.plays:data.defenses;const pb=$('playbook');pb.replaceChildren();for(const [key,v] of Object.entries(calls)){const btn=document.createElement('button');btn.type='button';btn.className='choice'+(play===key?' selected':'');const title=document.createElement('strong');title.textContent=v.name;const sub=document.createElement('small');sub.textContent=offense?(key==='run'?'Grind out yards':key==='pass'?'Attack downfield':key==='screen'?'Punish the blitz':'Surprise the defense'):(key==='blitz'?'Pressure the passer':key==='zone'?'Contain quick passes':'Stop the run');btn.append(title,sub);btn.onclick=()=>choose('play',key);pb.append(btn)}
 const list=$('abilities');list.replaceChildren();for(const p of data.options){const btn=document.createElement('button');btn.type='button';btn.className='choice'+(position===p.position?' selected':'');btn.disabled=p.cooldown>0;const title=document.createElement('strong');title.textContent=p.name+' · '+p.position;const sub=document.createElement('small');sub.textContent=p.cooldown?'⏳ '+p.cooldown+' snap(s) remaining':p.move+' — '+p.description;btn.append(title,sub);btn.onclick=()=>choose('position',p.position);list.append(btn)}$('snap').disabled=!play||!position||busy;$('selectedSummary').textContent=play&&position?calls[play]?.name+' + '+(data.options.find(p=>p.position===position)?.move||'Ability'):'Choose a play and Pokémon.'}
function field(g){$('ballMarker').style.left=(9+g.ball*.82)+'%';const root=$('fieldSprites');root.replaceChildren();const positions=['QB','RB','WR1','WR2','WR3','TE','LT','LG','C','RG','RT','DE1','DE2','DT1','DT2','LB1','LB2','LB3','CB1','CB2','FS','SS'];const coords={QB:[36,64],RB:[25,64],WR1:[22,16],WR2:[22,88],WR3:[28,32],TE:[36,82],LT:[40,30],LG:[40,42],C:[40,53],RG:[40,65],RT:[40,77],DE1:[56,23],DE2:[56,78],DT1:[56,42],DT2:[56,62],LB1:[68,25],LB2:[68,50],LB3:[68,75],CB1:[73,10],CB2:[73,91],FS:[83,35],SS:[83,67]};const ids=g.playerLineup;for(const pos of positions){const id=ids[pos];if(!id)continue;const point=coords[pos];const el=document.createElement('div');el.className='field-sprite';el.style.left=point[0]+'%';el.style.top=point[1]+'%';const img=document.createElement('img');img.src=sprite(id);img.alt=pos;img.loading='lazy';const label=document.createElement('small');label.textContent=pos;el.append(img,label);root.append(el)}}
function feed(g){const root=$('feed');root.replaceChildren();if(!g.log.length){root.textContent='Kickoff is coming. Choose your first play.';return}for(const e of g.log){const row=document.createElement('article');const title=document.createElement('strong');title.textContent='SNAP '+e.snap+' · '+(e.offense?'YOUR OFFENSE':'YOUR DEFENSE')+' · '+e.play;const p=document.createElement('p');p.textContent=e.pokemon+' used '+e.move+'. AI: '+e.aiCall+'. '+(e.yards>=0?'+':'')+e.yards+' yards. '+e.event;row.append(title,p);root.append(row)}}
function render(d){data=d;const g=d.game;const active=!!g; $('setup').hidden=active;$('game').hidden=!active;if(!g){msg('Choose an AI opponent and start a game.');return}$('myScore').textContent=g.score[0];$('aiScore').textContent=g.score[1];$('opponentName').textContent=g.team;$('clock').textContent='Q'+g.quarter+' · SNAP '+Math.min(g.snap+1,24)+'/24';$('situation').textContent=g.down+' & '+g.toGo+' · BALL '+g.ball;$('possession').textContent=g.turn==='offense'?'YOU HAVE THE BALL':'AI HAS THE BALL';$('callHeading').textContent=g.turn==='offense'?'CALL YOUR OFFENSE':'CALL YOUR DEFENSE';$('callHint').textContent=g.turn==='offense'?'Beat the AI defensive call to gain extra yards.':'Predict the AI play and shut it down.';field(g);feed(g);if(g.finished){msg('FINAL · '+(g.winner==='player'?'YOU WIN!':g.winner==='ai'?'AI WINS':'TIE')+' · '+g.score.join(' – '));$('snap').disabled=true;$('snap').textContent='FINAL WHISTLE';$('playbook').replaceChildren();$('abilities').replaceChildren();$('selectedSummary').textContent='Game complete. Start another showdown to play again.';return}msg('Q'+g.quarter+' · '+(g.turn==='offense'?'Your offense is on the field.':'Your defense is on the field.')+' Match progress saves automatically.');if(!d.options.some(p=>p.position===position&&p.cooldown===0))position='';play='';$('snap').textContent='🏈 SNAP THE BALL →';drawChoices()}
$('start').onclick=async()=>{if(busy)return;busy=true;try{msg('Setting up your game…');render(await api({action:'start',stage:Number($('opponent').value)}))}catch(e){msg(e.message)}finally{busy=false}};
$('snap').onclick=async()=>{if(busy||!play||!position)return;busy=true;$('snap').disabled=true;try{const result=await api({action:'snap',play,position});render(result);if(result.entry)msg(result.entry.pokemon+' used '+result.entry.move+' · '+result.entry.yards+' yards. '+result.entry.event)}catch(e){msg(e.message);drawChoices()}finally{busy=false;if(data?.game&&!data.game.finished)drawChoices()}};
$('newMatch').onclick=()=>{if(!data?.game?.finished&&!confirm('Start a new game? Your current game will be replaced.'))return;data=null;$('setup').hidden=false;$('game').hidden=true;msg('Choose your next AI opponent.')};
api().then(render).catch(e=>{msg(e.message+' Sign in and save your Dream Team to play.');$('setup').hidden=false})();})();