(()=>{'use strict';const $=id=>document.getElementById(id);let career=null,busy=false;
const api=async(action,data={})=>{const r=await fetch('/api/story',{method:action?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:action?JSON.stringify({action,...data}):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Career unavailable');return d};
function status(s){$('status').textContent=s}
function render(d){career=d.career;$('newCareer').hidden=!!career;$('career').hidden=!career;if(!career){status('Create your franchise to begin your saved story.');return}
const c=career,played=c.playedGames;$('chapterLabel').textContent='CHAPTER '+Math.min(12,c.chapter+1)+' / 12';$('chapterTitle').textContent=c.completed?'🏆 Hall of Champions':c.chapterTitle;$('narrative').textContent=c.completed?'Your franchise has entered the Hall of Champions. Every chapter, matchup, and title is preserved.':[
'An overlooked franchise offers you one chance to prove yourself. Win over the locker room and survive the opening campaign.',
'Ownership wants results. Your rebuilding plan is now under the spotlight.',
'Old rivals have circled your team on the calendar. Settle the score on the field.',
'The scouting department is divided. Trust your roster or search for the next superstar.',
'A trade rumor shakes the locker room. Keep the team focused through the uncertainty.',
'Every victory matters as the postseason picture begins to take shape.',
'The board demands a contender. One bad run could define your legacy.',
'The league has stopped underestimating you. Now they are hunting you.',
'Indigo Stadium awaits. Build a reputation that reaches beyond your home city.',
'Championship expectations have replaced underdog optimism. Can you build a dynasty?',
'Your veterans are legends. Their last run deserves a fitting ending.',
'The final chapter. Every choice, every game, and every title leads to this moment.'
][Math.min(c.chapter,11)]+(c.week===17?' Final week of the chapter: leave everything on the field.':c.week===0?' A new season begins.':' Next up: '+c.nextOpponent+'.');$('record').textContent=c.careerWins+'–'+c.careerLosses;$('progressFill').style.width=(played/c.totalGames*100)+'%';$('progressText').textContent=played+' of '+c.totalGames+' games · '+Math.round(played/c.totalGames*100)+'% complete'+(c.completed?' · CAREER COMPLETE':' · Season game '+(c.week+1)+'/18');for(const id of ['credits','reputation','morale','championships'])$(id).textContent=c[id];$('franchiseName').value=c.teams[0].name;$('opponent').textContent=c.completed?'Career Complete':'Week '+(c.week+1)+' · '+c.teams[0].name+' vs '+c.nextOpponent;$('decisionPanel').hidden=c.completed;
const choices=$('decisions');choices.replaceChildren();for(const opt of c.choices){const b=document.createElement('button');b.type='button';b.className=c.choice===opt.id?'selected':'';b.disabled=!!c.choice||c.credits<opt.cost;const strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=opt.title;small.textContent=opt.detail;b.append(strong,small);b.onclick=()=>mutate('decision',{decision:opt.id});choices.append(b)}$('playGame').disabled=!c.choice;$('watchLast').hidden=c.lastGame===null;$('watchLast').href='/dream-match.html?storyGame='+c.lastGame;$('rosterStatus').textContent='Your roster has 22 Pokémon. You can import your saved multiplayer Dream Team at any time; the GM roster is saved separately.';
const hist=$('history');hist.replaceChildren();for(let i=c.history.length-1;i>=0;i--){const g=c.history[i],row=document.createElement('div'),info=document.createElement('span'),link=document.createElement('a');info.textContent='Chapter '+(g.chapter+1)+' · Week '+g.week+' · '+c.teams[g.opponent].name+' · '+g.scores.join('–')+(g.won?' · WIN':' · LOSS');link.href='/dream-match.html?storyGame='+i;link.textContent='▶ Watch replay';row.append(info,link);hist.append(row)}if(!c.history.length)hist.textContent='Your story begins with your first kickoff.';status('✓ Career saved to your account. Your progress is restored when you return.')}
async function mutate(action,data){if(busy)return;busy=true;try{status('Saving career…');render(await api(action,data));if(action==='play')status('Match complete and saved! Watch the replay or prepare for the next game.')}catch(e){status(e.message)}finally{busy=false}}
$('startCareer').onclick=()=>mutate('start');$('rename').onclick=()=>mutate('name',{name:$('franchiseName').value});$('playGame').onclick=()=>mutate('play');
$('importRoster').onclick=async()=>{try{const r=await fetch('/api/my-team',{credentials:'same-origin'}),d=await r.json();if(!r.ok)throw Error(d.error||'Could not load team');if(!d.team)throw Error('Build and save your Dream Team first.');if(!confirm('Replace your GM career roster with '+d.team.name+'?'))return;await mutate('roster',{lineup:d.team.lineup})}catch(e){status(e.message)}};
api().then(render).catch(e=>{status(e.message);if(/Log in/i.test(e.message)){const a=document.createElement('a');a.href='/account.html?next=/story.html';a.textContent=' Log in to play →';$('status').append(a)}})})();